the_game_maps_maps:
    resource: "@TheGameMapsBundle/Controller/MapsController.php"
    type:     annotation

the_game_api:
    resource: "@TheGameAPIBundle/Controller/"
    type:     annotation
    prefix:   /

the_game_admin:
    resource: "@TheGameAdminBundle/Controller/"
    type:     annotation
    prefix:   /

the_game_maps:
    resource: "@TheGameMapsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
